services:
  # Base de Datos SQL
  db:
    image: mysql:8.0
    container_name: HDA_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: WilsonHDA2026
      MYSQL_DATABASE: hdassistant
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hda-net

  # ChromaDB (RAG)
  chroma:
    image: chromadb/chroma:latest
    container_name: HDA_chroma
    volumes:
      - ./chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
    networks:
      - hda-net

  # Ollama (GPU)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - hda-net

  # Tu Backend (Orquestador)
  backend:
    build: ./backend
    container_name: HDA_backend
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
    ports:
      - "5000:5000"
    networks:
      - hda-net

  # Tu Frontend (Interfaz Flask)
  frontend:
    build: ./frontend
    container_name: HDA_frontend
    depends_on:
      - backend
      - db
      - chroma
    ports:
      - "5001:5001"
    environment:
      - HOST=db
      - USER=root
      - PASSWORD=WilsonHDA2026
      - DATABASE=hdassistant
      # TODO IMPORTANTE: Dentro de Docker usa el nombre del servicio o localhost ????
      - URLIA=http://backend:5000
      - CHROMA_HOST=http://chroma:8000
    networks:
      - hda-net

# Definición de Redes y Volúmenes
networks:
  hda-net:
    driver: bridge

volumes:
  ollama_data:
  mysql_data: